name: tests

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Decrypt secrets
      run: |
        chmod +x ./.github/scripts/decrypt_key.sh
        chmod +x ./.github/scripts/decrypt_develop_key.sh
        ./.github/scripts/decrypt_key.sh
        ./.github/scripts/decrypt_develop_key.sh
      env:
        FIREBASE_DEVELOP_PASSPHRASE: ${{ secrets.FIREBASE_DEVELOP_PASSPHRASE }}
        FIREBASE_PASSPHRASE: ${{ secrets.FIREBASE_PASSPHRASE }}    
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create coverage report
      run: ./gradlew jacocoTestReport
    
    - name: Send report to Codacy
      run: |
        export CODACY_PROJECT_TOKEN=${{secrets.CODACY_KEY}}
        bash <(curl -Ls https://coverage.codacy.com/get.sh)
